### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by obbrbt** [2dogz/4320project3#3]
Data Inputted:

Please Enter a Stock Ticker Symbol: IBM
Please Enter a Chart Type (1, 2): 1
Please Enter a Chart Time Series(1, 2, 3, 4): 2
Enter the Start Date (YYYY-MM-DD): 2021-03-05
Enter the End Date (YYYY-MM-DD): 2021-03-05

Code throws this error: 
Traceback (most recent call last):
  File "main.py", line 170, in <module>
    if __name__ == '__main__':
  File "main.py", line 164, in main
    while keepGoing:
  File "main.py", line 156, in getJsonPage
    if 'Invalid API call' not in req.text:
  File "main.py", line 92, in makeGraph
    dateSplit = date.split(' ')[1]
IndexError: list index out of range

**Comment by obbrbt** [comment]
Make a function so that if it's not intraday, the start and end dates cannot be the same day.

**Comment by 2dogz** [comment]
fixed with [commit](https://github.com/2dogz/4320project3/commit/1853a63c4ca609392bac383316aa4b4aaaaba4dd)
